name: sonar-check

on:
  push:
    branches:
      - develop

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Versão do JDK
          distribution: 'adopt'

      - name: Run sonar-check
        run: |
          ./gradlew sonarqube \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=admin \
            -Dsonar.password=sqp_e1604d9ea3cdd4cc3ff82635c159a16df483849a

      - name: Upload SonarQube analysis results
        uses: actions/upload-artifact@v2
        with:
          name: sonarqube-report
          path: .scannerwork/report
