name: sonar-check

on:
  push:
    branches:
      - develop

jobs:
   sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: SonarQube Scanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=node-api \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=sqp_e1604d9ea3cdd4cc3ff82635c159a16df483849a


